
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!
CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL
);

CREATE TABLE "acts" (
	"id" SERIAL PRIMARY KEY,
	"acts" VARCHAR (200)
);

CREATE TABLE "user_acts" (
	"id" SERIAL PRIMARY KEY,
	"user_id" INT REFERENCES "user",
	"act_id" INT REFERENCES "acts",
	"complete" BOOLEAN default false
);

CREATE TABLE "favorites" (
	"id" SERIAL PRIMARY KEY,
	"act_id" INT REFERENCES "acts",
	"user_id" INT REFERENCES "user"
);


INSERT INTO acts (acts)
VALUES ('Hold the elevator door open for someone'), ('Leave kind messages on social media posts'), ('Write an appreciation card to your coworkers and friends'), ('Send your friend photos of themselves on their wedding day'), ('Pick up garbage you see on the floor'),
('Help with chores around the house'), ('Check in on a new mom or dad every couple of weeks so they don’t feel lonely'), ('Smile at strangers'), ('Buy a coffee for the person behind you'), ('Convince your work to fundraise for a  charity'), ('Bring muffins and coffee to work one morning for your coworkers'), ('Write a kind birthday message to someone on their birthday'), ('Send a thank you note to your former teacher'), ('Do the thing someone always nags you about'), ('Send a holiday or greeting card to kids in the hospital'), ('Leave extra change in a vending machine'), ('Listen with care to someone’s struggles'), ('Compliment a friend'), ('Buy a food gift basket for the family who recently lost someone'), ('Forgive someone who hurt you'), ('Give a generous tip to those working in the service industry'), ('Call a friend to see how they’re doing'), ('Send positive vibes to your enemy'), ('Leave books in a library mailbox '), ('Throw someone you care about a surprise party or birthday party'), ('Volunteer at a nonprofit'),
('Leave a positive review for a local business'), ('Donate blood'),
('Cheer on marathoners at the sidelines'), ('Visit an elderly relative at an old age home'), ('Gossip less'), ('Make people laugh'), ('Speak positively '),
('Love people with your whole heart'), ('Donate your old clothes'),
('Buy lunch for a homeless person'), ('Send someone thinking of you flowers'),
('Tell someone who once helped you that you’re doing well now'),
('Hold the door open for someone'), ('Mow your neighbors law or shovel their driveway'),
('Show up on time'), ('Allow a car to pass in front of you'), ('Bring flowers to a nursing home'), ('Create an 100 Reasons Why I Love You video for someone you care about'), ('Share compliments you hear from other people'), ('Check in on those who’ve lost parents on Mother’s and Father’s Day'), ('Write a long heartfelt message in a birthday or holiday card'), ('Share photos of a deceased family member that you have'),
('Offer your seat to a person in need on the bus'), ('Post on social media about the random acts of kindness you’ve received from strangers'), ('Donate money to your favorite charity'), ('Send a message to your coworkers boss to tell them a kind thing they did'),
('Buy or donate canned goods for a local food bank'), ('Invite someone over for dinner'),
('Spend time with loved ones'), ('Mentor or tutor someone who needs help'),
('Send a care package to a struggling friend'), ('Put a coin in an expired meter'),
('Teach someone something new'), ('Offer to drive the neighbors kids to school along with yours'), ('Return something you borrowed'),
('Apologize when you mess up'), ('Offer to babysit for a new parent'),
('Try letting go of a grudge'), ('Cook someone’s favorite meal'),
('Be someone’s personal cheerleader'),
('Encourage a coworker to go after a promotion'),
('Offer to take care of a friend’s pet when they’re on vacation'),
('Help someone with a project'),
('Be honest to everyone'),
('Give coupons that can be redeemed for your services for free such pep talk, massage, chores, etc.'),
('Always carry a second umbrella on rainy days to give to someone in need'),
('Dedicate a song to someone on the radio'),
('Throw a family party so people can make great memories together'),
('Let someone go ahead of you in line'),
('Write a funny or happy song about someone'),
('Draw someone a picture of themselves'),
('Leave positive messages in your children’s lunch bags'),
('Remind people what they’ve got going for them when they can’t see it'),
('Give someone a high five'),
('Recommend a colleague on LinkedIn'),
('Leave a thank you note for the postal worker'),
('Help an unemployed person get a job'),
('Play with your pet for an extended period'),
('Share the vegetables you’ve grown in your garden'),
('Tell someone “I love you”'),
('Remove hateful graffiti in your neighborhood'),
('Offer to fix something that broke'),
('Start your day by praising people you see'),
('Rescue an animal that’s in danger'),
('Put your phone away when you’re with someone'),
('Surprise someone with a bucket list activity'),
('Send birthday flowers to someone with no children'),
('Include someone in a conversation'),
('Stand up against someone being bullied'),
('Help pay for a student’s education'),
('Buy someone in need groceries'),
('Have a small pack of tissues in case you find someone crying'),
('Surprise someone  who can’t afford holiday presents with gifts'),
('Donate three month’s rent to someone who just lost a parent'),
('Stay on the phone until the early morning with someone who has PTSD'),
('Help someone with anxiety feel safe'),
('Be there for someone struggling with depression and suicidal thoughts'),
('Bring a special snack for a person with severe dietary restrictions'),
('Tell your kids bedtime stories'),
('Make breakfast in bed for your family'),
('Offer to take pictures of tourists struggling to take a selfie'),
('Leave a comment on a blog post you enjoyed'),
('Introduce two people who should meet each other'),
('Set two compatible friends up on a date'),
('Thank the janitor at your workplace or school'),
('Invite a new coworker to lunch'),
('Chat up the lonely or shy person in a room'),
('Buy something from your friend’s new business'),
('Write positive messages in chalk on the side walk'),
('Be patient with a difficult person'),
('Use reusable bags'),
('Bake cookies for your friends and family'),
('Donate toys to a children’s hospital'),
('Help a domestic abuse survivor feel safe'),
('Put a bird feeder in the yard'),
('Leave positive comments on a YouTube channel that regularly gets a lot of hate'),
('Grab a bunch of friends to do a photo day'),
('Believe in someone who doesn’t believe in themselves'),
('Hide positive bookmarks in random library books'),
('Plant a tree'),
('Donate bone marrow'),
('Be kind to yourself and take time for self care'),
('Thank your garbage man'),
('Send someone a photo of themselves'),
('Gift a picture of someone with a deceased family member on the anniversary of their death'),
('Speak highly of others when they’re being gossiped about'),
('Encourage someone to go after their dreams'),
('Give someone the benefit of the doubt'),
('Foster a child'),
('Adopt a pet'),
('Donate your hair to charity'),
('Check in on someone a few months after they’ve been divorced'),
('Create a scrapbook about your relationship with a loved one'),
('Buy someone dinner'),
('Leave a letter in your favorite book at the library'),
('Leave a book on a bus seat and around town'),
('Ask for the recipe of a delicious meal someone made '),
('Leave random kindness letters around town'),
('Buy lemonade from a kid’s lemonade stand'),
('Donate to a local charity'),
('Give small gift cards to random people for helping you, doing something kind, or who are just (awesome'),
('Do volunteer activities as a family to spread goodness at scale'),
('Give stickers to your child to pass out to all of his or her classmates'),
('Get to know someone'),
('Donate positive reading material to doctor’s office'),
('Message the wife or husband of a newly married friend telling them how lucky they are to have that person in their life '),
('Drop off a gift basket for firefighters or police station with goodies'),
('Turn off the water when it’s not being used'),
('Create kindness jars for your coworkers'),
('Hand deliver a get well card to a friend in the hospital'),
('Do a household chore without being asked'),
('Do a virtual video chat with a friend who recently moved to another country'),
('Buy school supplies for a teacher'),
('Run a marathon for a charity'),
('Create a homemade gift for someone'),
('Give someone who recently moved a tour of the city'),
('Watch someone else’s favorite show with them'),
('Pay for someone’s bus fare'),
('Leave some spare change on a wishing fountain'),
('Volunteer your time at a local animal shelter'),
('Leave a local business a positive online review'),
('Offer a bottle of water to your mail carrier or leave them a nice note in your mailbox'),
('Create care packages for friends and family members who work long hours, are struggling in life, or are in school'),
('Register yourself onto a bone marrow registry and potentially save someone’s life'),
('Bring food and water to a local fire station'),
('Give back with community service'),
('Take the neighbor’s dog for a walk or offer to babysit'),
('Leave sticky notes with sweet messages around the house to your spouse or kids'),
('Donate or give an old cell phone to someone who may need one'),
('Clean up dog poop around the area you live or in parks around your home'),
('Pick up plastic bags left around grocery stores or littered around parks and dispose them'),
('Create a free library for your local community such as a “take a book, leave a book” program'),
('Give your seat to someone random on a crowded bus'),
('Leave a positive comment on a blog post or YouTube video'),
('Make or bring someone in need a warm meal'),
('Leave a surprise note or encouraging note for a fellow colleague struggling at work'),
('Bring someone a hot chocolate or coffee on a cold day'),
('Clear out your food pantry and donate non-perishable food to a local shelter'),
('Check in on an elderly neighbor and offer to fix things around their house or buy them groceries'),
('Write letters of appreciation to companies whose services or products you’ve been enjoying'),
('Offer to clean at a local homeless shelter'),
('Have an extra umbrella available for colleagues at work or strangers on a rainy day'),
('Be generous and give an extra tip to someone working in the service sector'),
('Sign up to be an organ donor'),
('Let a car merge ahead of you in a drive-thru or on a highway'),
('Offer to carry a stranger’s grocery bags to their car'),
('Call or message an old friend you haven’t heard from in a while and check in on how they’re doing');
